apiVersion: v1
data:
  appsettings.Production.json: "{\r\n  \"Logging\": {\r\n    \"LogLevel\": {\r\n      \"Default\":
    \"Information\",\r\n      \"Microsoft\": \"Warning\",\r\n      \"Microsoft.Hosting.Lifetime\":
    \"Information\"\r\n    }\r\n  },\r\n  \"AllowedHosts\": \"*\",\r\n  \"DatabaseConfig\":
    \ {\r\n      \"DBURL\": \"10.0.0.2\",\r\n      \"DBUserName\": \"admin\",\r\n
    \     \"DBPassword\": \"password\"\r\n  }\r\n}\r\n"
kind: ConfigMap
metadata:
  name: appsettings
  namespace: default
